# Generated by Django 4.1.6 on 2023-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=250)),
                ('food_type', models.CharField(max_length=250)),
                ('calorie', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
