# Generated by Django 4.1.6 on 2023-02-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activityitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=250)),
                ('calorie', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=250)),
                ('calorie', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFooditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=250)),
                ('food_type', models.CharField(max_length=250)),
                ('calorie', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
