# Generated by Django 4.1.6 on 2023-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activityitems_useractivityitems_userfooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='protein',
            field=models.FloatField(),
        ),
    ]
